// client-js/src/App.jsx
import {
  ApolloClient,
  InMemoryCache,
  ApolloProvider,
} from "@apollo/client";
import BookList from './components/BookList'
import Form from './components/Form'

// apollo client setup
const client = new ApolloClient({
  uri: 'http://localhost:4000/graphql',
  cache: new InMemoryCache()
});


const App = () =>{
  return (
    <ApolloProvider client={client}>
      <BookList />
      <Form className="absolute bottom-0" />
    </ApolloProvider>
  )
}

export default App

// client-vue/src/App.vue
<script setup lang="ts">
import { watch } from "vue";
import BookList from "./components/BookList.vue";
import Form from "./components/Form.vue";
import { useQuery } from "@vue/apollo-composable";
import gql from "graphql-tag";

const { result } = useQuery(gql`
  {
    books {
      name
      id
    }
  }
`);

watch(() => {
  console.log(result.value);
});
</script>

<template>
  <BookList />
  <Form class="absolute bottom-0" />
</template>

<style></style>
